declare const styles: {
  readonly "article": string;
  readonly "body": string;
  readonly "breadcrumb": string;
  readonly "cover": string;
  readonly "footerWrap": string;
  readonly "hero": string;
  readonly "linkCardInline": string;
  readonly "linkCardStandalone": string;
  readonly "linkMeta": string;
  readonly "linkThumb": string;
  readonly "linkTitle": string;
  readonly "linkUrl": string;
  readonly "medium": string;
  readonly "publishedDate": string;
  readonly "rawLink": string;
  readonly "sectionCard": string;
  readonly "sectionTitle": string;
  readonly "surface": string;
  readonly "tagChip": string;
  readonly "tags": string;
  readonly "title": string;
};
export = styles;
