name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
  pull_request_review_comment:
    types: [created]

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: fluxninja/openai-pr-reviewer@0.54.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          review_simple_changes: false
          review_comment_lgtm: false
          disable_review: true
          summarize_release_notes: |
            Create concise release notes in `markdown` format for this pull request, 
            focusing on its purpose and user story. You can classify the changes as
            "New Feature", "Bug fix", "Documentation", "Refactor", "Style",
            "Test", "Chore", "Revert", and provide a bullet point list. For example:
            "New Feature: An integrations page was added to the UI". Keep your
            response within 50-100 words. Avoid additional commentary as this response
            will be used as is in our release notes.
